//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// GameEditor.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GameEditorTYPE              130
#define IDD_DIALOG_WORLDOBJECT          310
#define IDD_DIALOG_DETAILOBJ            311
#define IDD_DIALOG_TOOLBAR              312
#define IDD_DIALOG_ANIM2DEDITOR         314
#define IDD_DIALOG_PLAYER_EDITOR        316
#define IDD_DIALOG_SCENEEDITOR          318
#define IDD_DIALOG_ANIMCOMBINEEDIT      320
#define IDC_TREE_WORLDOBJECT            1000
#define IDC_TREE_COMPONENT              1001
#define IDC_EDIT_SCALE_X                1002
#define IDC_EDIT_ROTATION_X             1003
#define IDC_BUTTON_LOAD                 1003
#define IDC_EDIT_POS_X                  1004
#define IDC_BUTTON_SAVE                 1004
#define IDC_EDIT_SCALE_Y                1005
#define IDC_BUTTON_SAVE2                1005
#define IDC_BUTTON_ANIMSTOP             1005
#define IDC_EDIT_ROTATION_Y             1006
#define IDC_STATIC_FILENAME             1006
#define IDC_EDIT_POS_Y                  1007
#define IDC_STATIC_IMAGE_WIDTH          1007
#define IDC_EDIT_SCALE_Z                1008
#define IDC_STATIC_IMAGE_HEIGHT         1008
#define IDC_EDIT_ROTATION_Z             1009
#define IDC_STATIC_FILENAME2            1009
#define IDC_EDIT_POS_Z                  1010
#define IDC_STATIC_RCOLORKEY            1010
#define IDC_BUTTON_COLORKEY             1011
#define IDC_BUTTON_CUTSAVE              1012
#define IDC_LIST_CUTINFO                1013
#define IDC_STATIC_FILENAME4            1014
#define IDC_STATIC_GCOLORKEY            1015
#define IDC_STATIC_FILENAME6            1016
#define IDC_STATIC_BCOLORKEY            1017
#define IDC_STATIC_FILENAME3            1018
#define IDC_BUTTON_CUTLISTCLEAR         1019
#define IDC_STATIC_CUTLEFT              1020
#define IDC_LIST_PIVOTINFO              1021
#define IDC_BUTTON_PIVOTLISTCLEAR       1022
#define IDC_EDIT_PIVOTX                 1023
#define IDC_BUTTON5                     1024
#define IDC_BUTTON_PIVOTALLSAVE         1024
#define IDC_EDIT1                       1025
#define IDC_EDIT_PLAYRATE               1025
#define IDC_EDIT_XPOS                   1025
#define IDC_STATIC_FILENAME5            1026
#define IDC_EDIT_YPOS                   1026
#define IDC_STATIC_CUTTOP               1027
#define IDC_STATIC_FILENAME7            1028
#define IDC_STATIC_CUTRIGHT             1029
#define IDC_STATIC_FILENAME8            1030
#define IDC_STATIC_CUTBOTTOM            1031
#define IDC_BUTTON_PRINTCUTINFO         1032
#define IDC_STATIC_FILENAME9            1033
#define IDC_STATIC_FILENAME10           1034
#define IDC_EDIT_PIVOTY                 1035
#define IDC_BUTTON_PRINTPIVOTINFO       1036
#define IDC_BUTTON6                     1037
#define IDC_BUTTON_PIVOTSAVE            1037
#define IDC_EDIT2                       1038
#define IDC_EDIT_PLAYTIME               1038
#define IDC_RADIO1                      1039
#define IDC_RADIO_LOOP                  1039
#define IDC_RADIO2                      1040
#define IDC_RADIO_STOP                  1040
#define IDC_BUTTON_SAVE3                1041
#define IDC_BUTTON_ANIMPLAY             1041
#define IDC_EDIT_PIVOTX2                1042
#define IDC_EDIT_ANIMNAME               1042
#define IDC_LIST_ALLANIM                1047
#define IDC_UPPERBODY_ANIM              1048
#define IDC_LIST_UPPERANIM              1049
#define IDC_BUTTON_ADDUPPERANIM         1050
#define IDC_BUTTON_REMOVEUPPERANIM      1051
#define IDC_BUTTON_ANIMRESOURCESET      1051
#define IDC_LOWERBODY_ANIM              1052
#define IDC_STATIC_SEQUENCEFILENAME     1052
#define IDC_LIST_ALLANIM2               1053
#define IDC_BUTTON_PARENTANILOAD        1053
#define IDC_LIST_LOWERANIM              1054
#define IDC_BUTTON_ADDLOWERANIM         1055
#define IDC_BUTTON_PLAY                 1055
#define IDC_BUTTON_REMOVELOWERANIM      1056
#define IDC_BUTTON_STOP                 1056
#define IDC_BUTTON_UPPEERSAVE           1057
#define IDC_BUTTON_CHILDANILOAD         1057
#define IDC_BUTTON_LOWERSAVE            1059
#define IDC_STATIC_PARENTANINAME        1060
#define IDC_STATIC_CHILDANINAME         1061
#define IDC_LIST_PARENTANI              1062
#define IDC_LIST_CHILDANI               1063
#define IDC_BUTTON_ZOOMIN               1064
#define IDC_BUTTON_INSERT               1065
#define IDC_BUTTON_ZOOMOUT              1066
#define IDC_BUTTON_INSERT2              1067
#define IDC_BUTTON_ALLINSERT            1067
#define ID_32771                        32771
#define ID_Menu                         32772
#define ID_SAVE                         32773
#define ID_LOAD                         32774
#define ID_32775                        32775
#define ID_ANIMATION2D_EDITOR           32776
#define ID_32777                        32777
#define ID_PLAYER_EDITOR                32778
#define ID_32779                        32779
#define ID_SCENE                        32780
#define ID_32781                        32781
#define ID_ANIM2DCOMBINEEDIT            32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        322
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
